export { DEFAULT_EXTRACTION_HEURISTICS, extractJsonCandidates } from "./extract";
export {
  DEFAULT_SCHEMA_INSTRUCTION,
  formatPrompt,
  resolveSchemaInstruction,
  withFormat,
  type WithFormatOptions,
} from "./format";
export { extractFirstMarkdownCode, extractMarkdownCodeBlocks } from "./markdown";
export { sanitizeThink } from "./think";
export { normalizeModelOutput, withoutTrailingThinkTagPrefix } from "./generate-output";
export { createLLM, type CreateLLMOptions, type LLMClient } from "./llm";
export { generate } from "./generate";
export { formatZodIssues, parseLLMOutput } from "./parse";
export {
  createMCPClient,
  wrapMCPClient,
  type CreateMCPClientOptions,
  type MCPClientInfo,
  type MCPInMemoryTransportConfig,
  type MCPStdioTransportConfig,
  type MCPStreamableHTTPTransportConfig,
  type MCPTransportConfig,
  type ManagedMCPToolClient,
} from "./mcp";
export { images, resizeImage, type ImageInput, type ImageSize } from "./image";
export { conversation, type ConversationEntry } from "./conversation";
export { dedent, prompt, type PromptMessageBuilder } from "./prompt";
export { s, inspectSchemaMetadata, inferSchemaExample } from "./schema-builder";
export {
  buildDefaultStructuredPrompt,
  DEFAULT_LOOSE_PARSE_OPTIONS,
  DEFAULT_SELF_HEAL_BY_MODE,
  DEFAULT_SELF_HEAL_CONTEXT_LABEL,
  DEFAULT_SELF_HEAL_FIX_INSTRUCTION,
  DEFAULT_SELF_HEAL_MAX_CONTEXT_CHARS,
  DEFAULT_SELF_HEAL_NO_ISSUES_MESSAGE,
  DEFAULT_SELF_HEAL_PROTOCOL,
  DEFAULT_SELF_HEAL_RAW_OUTPUT_LABEL,
  DEFAULT_SELF_HEAL_RETURN_INSTRUCTION,
  DEFAULT_SELF_HEAL_STOP_ON_NO_PROGRESS,
  DEFAULT_SELF_HEAL_VALIDATION_LABEL,
  DEFAULT_STRICT_PARSE_OPTIONS,
  DEFAULT_STRUCTURED_OBJECT_INSTRUCTION,
  DEFAULT_STRUCTURED_STYLE_INSTRUCTION,
  buildSelfHealPrompt,
  structured,
  StructuredParseError,
  type BuildDefaultStructuredPromptOptions,
  type SelfHealPromptTextOptions,
} from "./structured";

export {
  createOpenAICompatibleAdapter,
  type OpenAICompatibleAdapterOptions,
} from "./providers/openai-compatible";
export {
  createAnthropicCompatibleAdapter,
  DEFAULT_ANTHROPIC_MAX_TOKENS,
  DEFAULT_ANTHROPIC_VERSION,
  type AnthropicCompatibleAdapterOptions,
} from "./providers/anthropic-compatible";
export { DEFAULT_MAX_TOOL_ROUNDS } from "./providers/mcp-runtime";
export {
  createDefaultProviderRegistry,
  createModelAdapter,
  createProviderRegistry,
  registerBuiltinProviders,
  type BuiltinProviderKind,
  type ModelAdapterConfig,
  type ProviderFactory,
  type ProviderRegistry,
  type ProviderTransportConfig,
} from "./providers/registry";

export type {
  CandidateDiagnostics,
  EmbeddingRequest,
  EmbeddingResult,
  LLMImageContent,
  LLMMessageContent,
  LLMReasoningEffort,
  LLMTextContent,
  ExtractJsonCandidatesOptions,
  ExtractionCandidate,
  ExtractionHeuristicsOptions,
  ExtractionParseHint,
  HTTPHeaders,
  LLMAdapter,
  LLMMessage,
  LLMRequest,
  LLMResponse,
  LLMStreamCallbacks,
  LLMStreamChunk,
  LLMToolCall,
  LLMToolCallRef,
  LLMToolDebugOptions,
  LLMToolExecution,
  LLMToolOutputTransformer,
  LLMToolArgumentsTransformer,
  LLMToolCallParamsTransformer,
  LLMToolChoice,
  MCPCallToolParams,
  MCPListToolsResult,
  MCPToolClient,
  MCPToolDescriptor,
  MCPToolSchema,
  LLMUsage,
  MarkdownCodeBlock,
  MarkdownCodeOptions,
  ParseLLMOutputOptions,
  ParseLLMOutputResult,
  ParseTraceEvent,
  PipelineError,
  ReasoningBlock,
  StreamTurnTransition,
  StructuredAttempt,
  StructuredCallOptions,
  StructuredDebugOptions,
  StructuredError,
  StructuredMode,
  StructuredOptions,
  StructuredPromptBuilder,
  StructuredPromptContext,
  StructuredPromptPayload,
  StructuredPromptResolver,
  StructuredPromptValue,
  StructuredResult,
  StructuredStreamData,
  StructuredStreamDelta,
  StructuredStreamEvent,
  StructuredStreamInput,
  StructuredStreamOptions,
  StructuredStreamSnapshot,
  StructuredSelfHealInput,
  StructuredTimeoutOptions,
  ThinkDiagnostics,
  ThinkBlock,
  StructuredTraceEvent,
  GenerateAttempt,
  GenerateCallOptions,
  GenerateOptions,
  GenerateResult,
  GenerateStreamDelta,
  GenerateStreamEvent,
  GenerateStreamInput,
  GenerateStreamOptions,
  GenerateStreamSnapshot,
  GenerateTraceEvent,
} from "./types";
